### ISSUE TITLE
No reaction of the windows 10 host when using input_keyboard.py

### ISSUE THREAD

**Issue by jcl-concept** [milador/RaspberryPi-Joystick#1]
Hi Milador,

Thank you for sharing this solution. I'm going to use it to simulate joystick buttons for a lap counter software (UR30) in a slot car projet.

The virtual joystick appears in WIndows 10 control panel but there is no reactions of the button when i use the small tests program input_keyboard.py. Whatever i type through my SSH session on the raspbeery PiZero, i've never seen the button light on in the windows 10 joystick control panel....

The /dev/hidg0 is here and no errors in dmesg and from input_keyboard.py
I'm using an Raspbian Buster.

Any ideas ?

Thank you for your help.
Jean-Christophe

**Comment by milador** [comment]
Hi Jean,

Can you double check the permission rules of the files (input_keyboard.py)? I have not tested it with latest version of Raspbian but It but should be fine. Try adding prints for buttons and see if it prints them.

**Comment by jcl-concept** [comment]
Hi,

i don't know why but this morning, the same script i used yesterday is working as attended 😕😊.

Strange, i'm going to search further to understand.... maybe the chmod g+rw on the /dev/hidg0 i did yesterday morning but it didnt change anything yesterday...

Thanks anyway.

Best regards,
Jean-Christophe

**Comment by milador** [comment]
Oh you probably needed to do a reboot to make it work or just a simple permission issue. 

I am glad you got it working.

Let me know if you come up with ways to improve the setup.

I will add a new code in next few months to have a joystick hid to joystick hid adapter.

I close this issue for now.
