### ISSUE TITLE
Rpi not being recognized as joystick

### ISSUE THREAD

**Issue by Krakers665** [milador/RaspberryPi-Joystick#2]
Hello, 
After following the installation my rpi zero W is being recognized as serial COM device (RNDIS/Ethernet gadget). 
Tried to install it several times and checked on two windows10 PCs.

Which version of raspbian did you use?
I'm not sure where the problem is

**Comment by milador** [comment]
Double check the descriptor again. I have tested it with raspbian release from May and it worked fine.
Try rebooting it after making changes as well.

**Comment by Krakers665** [comment]
Tried also with raspbian buster (2020-02-13) on raspberry pi zero W and now device is not being recognized because of "a request fot the USB device descriptor failed". Tried few times with different OTG cables. So still stuck on point 7...

aaand while typing that that i just set sleep time in /usr/bin/xac_joystick_usb for 30 and it apeears as "XAC Virtual Joystick". I'll test it later, but seems working! Thank you

@edit
OK, couldn't sleep. Works like a charm. Thanks a lot!

**Comment by milador** [comment]
Thanks for feedback. Glad you got it working.
