### ISSUE TITLE
[Suggestion] Merge all versions into one

### ISSUE THREAD

**Issue by NeoTechni** [milador/RaspberryPi-Joystick#21]
I'd like the ability to make one program that can switch between any of the modes, like the Titan Two

**Comment by milador** [comment]
@NeoTechni That is a great suggestion. I am planning to turn this to it's own OS and I will try to add that option. I believe the raspberry pi needs to be reset in that case. Unless it's in composite HID Mode.

**Comment by NeoTechni** [comment]
That's fine. I doubt many people will need to use it on 2 consoles at the same time.
