### ISSUE TITLE
[Suggestion] Act as a composite keyboard+controller device

### ISSUE THREAD

**Issue by NeoTechni** [milador/RaspberryPi-Joystick#22]
That way you can use the keyboard for controls, and switch over to it acting as a keyboard for chatting, and back again when you're done

**Comment by milador** [comment]
@NeoTechni Great example. Some devices don't accept composite devices, but the user can use

**Comment by milador** [comment]
@NeoTechni So the host device accepts both keyboard and gamepad in this case. Good Example. Thanks
