### ISSUE TITLE
Cannot access x_buttons_rpi_joystick_usb: No such file or directory

### ISSUE THREAD

**Issue by 0marA** [milador/RaspberryPi-Joystick#24]
When I run all of the commands, I can only get as far as step 5 before I get this error.

sudo chmod +x 16_buttons_rpi_joystick_usb
chmod: cannot access '16_buttons_rpi_joystick_usb': No such file or directory

**Comment by milador** [comment]
Take a look at /usr/bin/ directory to see if the file exist. You may need to use sudo su in step 4 depending on your user account permissions.
