### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by alexander-denev** [milador/RaspberryPi-Joystick#27]
Hello!

I've stumbled upon this awesome project and I'd like some help with using it.

How do I configure the association between keyboard keys and gamepad buttons?

Thanks!

**Comment by milador** [comment]
@fugzel You have two options:

1. Edit the inputevent.py files and restarting the raspberry pi. As an example, you can change EIGHT_BUTTON.BOne in EVENT2ACTION to EIGHT_BUTTON.BTwo for : [joystick_8_buttons_inputevent.py](https://github.com/milador/RaspberryPi-Joystick/blob/master/8_Buttons_Joystick/Code/joystick_8_buttons_inputevent.py).
2. Use [custom OS](http://bluestick.ca/) which includes everything for you and edit yml files under **/usr/local/etc/BlueStick/resource/main/config/** using text editor.
Hope it helps!
