### ISSUE TITLE
ls: cannot access '/dev/hidg*': No such file or directory

### ISSUE THREAD

**Issue by moeiscool** [milador/RaspberryPi-Joystick#9]
I have followed the tuts for NSGamePad, 32 button and 16 button (filling in TBD manually) but I can't seem to get the device to do anything other than show "Device Descriptor Request Failed" on my windows 10 computer. Am I missing something?

**Comment by milador** [comment]
Can you try the following : 
`sudo chmod 666 /dev/hidg0`

This can be user permission issue and make sure you reboot.

This will need to be repeated on every boot however. I will have instructions on how to make it run the rules by itself.

I am updating the instructions as there has been lots of changes. Check in back in few days.

**Comment by moeiscool** [comment]
```
root@raspberrypi:/sys/kernel/config/usb_gadget/xacgamepad# sudo chmod 666 /dev/hidg0
chmod: cannot access '/dev/hidg0': No such file or directory
root@raspberrypi:/sys/kernel/config/usb_gadget/xacgamepad# sudo chmod 666 /dev/hidg0
chmod: cannot access '/dev/hidg0': No such file or directory
```

```
root@raspberrypi:/sys/kernel/config/usb_gadget/xacgamepad# ls -la /dev/hid*
crw------- 1 root root 244, 0 Feb 22 05:15 /dev/hidraw0
crw------- 1 root root 244, 1 Feb 22 05:15 /dev/hidraw1
````

I forgot to mention I am on Raspberry Pi 4, not Zero

I am running as root. Thank you, I will wait for your update :) Cheers!

**Comment by milador** [comment]
I have not done a lot of testing on Raspberry Pi 4. Thanks for letting me know. I repeat the installation from scratch on RPi 4 to check what is the issue.

**Comment by gdsports** [comment]
I have never tried USB gadget on a Pi4. Is there an easy to use breakout to access the USB data wires versus power? I rather not cut up a cable and accidentally short the power.

**Comment by milador** [comment]
@gdsports maybe [USB Micro-B Breakout Board](https://www.adafruit.com/product/1833) can help. Something like this can help: [Is it me or is it USB](https://www.tindie.com/products/nerfhammer/is-it-me-or-is-it-usb/)

I am starting to test USB and Rpi 4 next week. 

This spliter can work for Zero: [splitter](https://www.amazon.ca/dp/B00OZDUTMM/)

**Comment by moeiscool** [comment]
I read online the USB-C port can be used for OTG on the Pi 4
https://www.raspberrypi.org/forums/viewtopic.php?t=243966

**Comment by milador** [comment]
@moeiscool yes, it should work according to documentations. I am trying it today with a USB hub. Ordered the spliter to test it out. I believe there is one step missing in my instructions.

**Comment by gdsports** [comment]
@milador @moeiscool I figured out the no hidg0 device problem. I will push a PR. usb_f_hid.ko driver is different for PiZ versus Pi4. The usb_f_hid.ko currently in the repo only works for PiZ.

The other problem is the XAC does not supply enough power out its USB port even when the XAC is powered by a 5V 2A wall adapter. The Pi4 draws over 600 mA when booting up which exceeds the XAC's 500 mA limit. The Pi4 LEDs flash but it never finishes booting.

A Pi4 does boot plugged to my desktop PC which also has a 500 mA limit but I guess it is more tolerant of a power hungry device. A Pi4 also booted when plugged into a powered USB hub with a high-power USB port capable of supplying up to 1.5A.

The USB hub does not work when plugged into the XAC so this is not an option.

A USB Y cable might be able to draw power from both XAC ports assuming the XAC  is powered by a 5V 2A wall adapter. I have on on order.

https://www.amazon.com/Black-Female-Extension-Mobile-CableCC/dp/B00ZUE6PVE/

PR #10 is up.

**Comment by milador** [comment]
@gdsports good call. I just realized that for pi4 it's built using `make bcm2711_defconfig`. I wait for your push and try to build it myself as well. We probably need to do the same for pi2 and pi3.

I actually used the USB Hub (not powered hub) with ios to fix the power issue when an arduino micro is plugged to it. I basically connected one port and left the other ones. A simple USB Spliter should work and I have one of those you mentioned.

**Comment by milador** [comment]
@gdsports wow, you beat me to it with pi2 and pi3 :) great work

**Comment by gdsports** [comment]
@milador Thanks, I hope it works now.

BTW, I use this for measuring USB current. It has type A and type C connectors. I rarely used until recently when I am figuring out why Pi boards do not boot when connected to an XAC.

https://www.amazon.com/Functional-Multimeter-Capacity-Temperature-Detector/dp/B07TS17VB9/

**Comment by milador** [comment]
I have one of those multi-meters but it's not USB C. I guess it's time for upgrade! 

Actually I don't think Rpi 2 and 3 work as they don't have USB OTG.

**Comment by gdsports** [comment]
I heard the 3+ model A can do USB gadget but it requires an unusual cable: Type A plug to Type A plug. But I do not have one.

**Comment by gdsports** [comment]
The Pi4 board is unique among Pi boards in that it can do USB Host and gadget at the same time. It is like a Teensy 3.6 but larger, more powerful, and uses much more power. For example, the Pi4 can convert a USB Kensington trackball for use with an XAC.

**Comment by milador** [comment]
@gdsports I am waiting for Y splitter and the USB Type A plug to Type A to Rpi3 and Rpi4.

**Comment by milador** [comment]
@moeiscool @gdsports Both USB and BT Mice are tested and both work on pi4 using that Y cable. I am adding steps for connecting cables. @moeiscool make sure the USB cable is connected before you run the code or you get 108 error.

**Comment by milador** [comment]
@moeiscool @gdsports USB keyboard works as well on pi 4.

**Comment by gdsports** [comment]
@milador Fast work on that Y cable.

The Pi4 is very close to being an Open Source Adaptive Controller.

The Pi4 USB gadget port connects to the console using a Mayflash adapter. The Mayflash supports PS4 and Nintendo Switch.

The Pi4 USB host ports support various USB joysticks, trackballs, trackpads, keyboards, mice, etc. The XAC USB ports only support USB joysticks.

The Pi4 BT supports BT HID keyboards and mice. The XAC does not support BT HID devices.

The Pi4 GPIOs supports switches and arcade buttons. This is the only option that requires extra hardware such as a HAT PCB with 1/8" jacks.

An alternate solution for arcade buttons is to use an arcade control kit like this one https://www.amazon.com/dp/B07JFXQSM5/. Two sets of USB joystick controllers, sticks, and buttons. No soldering required. The sticks are 8 way digital but reported by the USB controller as analog. This means WASD type control but it should be fine for casual gaming.

The Pi4 lacks analog inputs for analog joysticks. It is much easier for people to connect off-the-shelf USB joysticks so I do not see this as problem.

**Comment by milador** [comment]
That's a good idea and the only issue that I see is connecting multiple parts together ( Mayflash and rpi4 ). The great thing about XAC is that it's easy to setup and it works by simply plugin the device. There are many people that would benefit from this but they won't be able to put it together. 

This is of-course open source option and no point comparing the setup process with a commercial product. However, the setup process could be minimized so more people would be able to use it. 

I made a custom PCB (requires soldering) to turn raspberry pi zero w to adaptive controller just about time that XAC was introduced and I stopped working on it.  Here is the link if you want to take a look : [Open-GCI](https://github.com/milador/Open-GCI)

I used Brook Universal Fighting Board instead of Mayflash and unfortunately it doesn't have analog stick options.

I am thinking to design a new version of PCB with ADC for analog inputs which would work perfect with your NS gamepad and Mayflash adapter.

**Comment by moeiscool** [comment]
:( i was looking through the commits and saw the license changed. Sorry for getting you into this issue but I don't think I can use this project anymore. Cheers guys

**Comment by milador** [comment]
@moeiscool The idea was to add additional hardware and the license was for hardware component. I don't mind anyone using the software/code. I will basically make the hardware as a separate project and keep this project under MIT license. Go ahead and use use it:)

**Comment by gdsports** [comment]
Support for all Pi boards with USB gadget was going to be done anyway so there is no extra work here. The PiZW is great but hard to get quantity > 1 per order.
